// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxghhevwlwfpjvlcuspq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4Z2hoZXZ3bHdmcGp2bGN1c3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTk5MTIsImV4cCI6MjA3MTg5NTkxMn0.TYJnjfIxkecf-kWPyMP6q_SE2VGa5oiPqeSuhNzu1KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});